Update CI.yml

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -1,69 +1,73 @@
-# This is a basic workflow to help you get started with Actions
-
 name: CI
 
-# Controls when the workflow will run
 on:
-  # Triggers the workflow on push or pull request events but only for the "main" branch
   push:
     branches: [ "main" ]
   pull_request:
     branches: [ "main" ]
-
-  # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
   build:
-    # The type of runner that the job will run on
     runs-on: ubuntu-latest
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - name: Checkout code
         uses: actions/checkout@v4
 
-      # Sets up Python environment
       - name: Set up Python
         uses: actions/setup-python@v2
         with:
           python-version: '3.8'
 
-      # Installs the necessary dependencies
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install scikit-learn pandas numpy matplotlib seaborn keras tensorflow cvxopt
 
-      # Downloads the dataset from an external source
+  data:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Create data directory
+        run: mkdir -p data
+
       - name: Download dataset
         run: |
-          mkdir -p data
-          curl -L -o data/dataset.zip https://uni-siegen.sciebo.de/s/HGdUkoNlW1Ub0Gx
-          unzip data/dataset.zip -d data
+          curl -L -o data/dataset.zip https://uni-siegen.sciebo.de/s/HGdUkoNlW1Ub0Gx/download
+          if file data/dataset.zip | grep -q 'Zip archive data'; then
+            echo "Valid ZIP file."
+          else
+            echo "Invalid ZIP file. Exiting."
+            exit 1
+          fi
 
-      # Converts the Jupyter notebook to a Python script and runs it
+      - name: Unzip dataset
+        run: unzip data/dataset.zip -d data
+
+  run:
+    runs-on: ubuntu-latest
+    steps:
       - name: Run Jupyter notebook
         run: |
           pip install nbconvert
           jupyter nbconvert --to script eda_signal_classification.ipynb
           python eda_signal_classification.py
 
-      # Validates and cleans Jupyter notebooks
+  lint:
+    runs-on: ubuntu-latest
+    steps:
       - name: Ensure Clean Jupyter Notebooks
         uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1
         with:
           paths: '**/*.ipynb'
 
-      # Generates a changelog diff for the Jupyter notebooks
+  changelog:
+    runs-on: ubuntu-latest
+    steps:
       - name: Get changelog diff
-        uses: jupyter-naas/get-chagelog-diff@v1.0.0
+        uses: jupyter-naas/get-changelog-diff@v1.0.0
         with:
-          github_token: ${{ secrets.TOKEN_GITHUB }}
+          github_token: ${{ secrets.GITHUB_TOKEN }}
 
-      # Converts Jupyter Notebooks to PDF format
       - name: Jupyter Notebooks to PDF
-        uses: MohamedElashri/Jupyter-to-PDF@v1.3
+        uses: MohamedElash
